pipelines:
  default:
    - step:
        name: 'Mirror to GitHub repo...'
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --branch="master" --bare git@bitbucket.org:davordavidovic/batched-gemm-montecarlo.git
          - cd batched-gemm-montecarlo.git
          - git config push.default upstream
          - git push git@github.com:HybridScale/Entanglement-Cooling-Algorithm.git master
