pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:davordavidovic/batched-gemm-montecarlo.git
          - cd batched-gemm-montecarlo.git
          - git push --mirror git@github.com:HybridScale/Entanglement-Cooling-Algorithm.git master